### ISSUE TITLE
Add section "Workshops and Trainings"

### ISSUE THREAD

**Issue by RybkaRozarka** [just-paja/polocas-napadu-web#14]
There Is only section for performances - it Is different kind of information, so it is better not to mix it up.

**Comment by ReadyPlayerNaN** [comment]
As of https://github.com/just-paja/polocas-napadu-api/commit/45d8f95ba36ecbb3ba759b6fa3e9e78f28aeedc7 we can create workshops in paralel to shows. Unfortunately, they are not displayed yet.

**Comment by ReadyPlayerNaN** [comment]
Moved to redmine
